---
- hosts: localhost
  connection: local
  vars:
    resource_group_name: myrg100
    app_name: myTestApp
    location: eastus
    linux_plan_name: myTestPlan
    traffic_manager_profile_name: myTMProfile
    traffic_manager_endpoint_name: endpoint1
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      location: "{{ location }}"

  - name: Create resource group for app service plan
    azure_rm_resourcegroup:
      name: "{{ resource_group_name }}"
      location: "{{ location }}"

  - name: Create App Service Plan
    azure_rm_appserviceplan:
      resource_group: "{{ resource_group_name }}"
      name: "{{ linux_plan_name }}"
      location: "{{ location }}"
      is_linux: true
      sku: S1
      number_of_workers: 1

  - name: Create a Linux web app with Java framework and Tomcat
    azure_rm_webapp:
      resource_group: "{{ resource_group_name }}"
      name: "{{ app_name }}"
      plan:
        resource_group: "{{ resource_group_name }}"
        name: "{{ linux_plan_name }}"
      app_settings:
        testkey: "testvalue"
      frameworks:
        - name: java
          version: 8
          settings:
            java_container: "Tomcat"
            java_container_version: "8.5"

  - name: Get web app facts
    azure_rm_webapp_facts:
      resource_group: "{{ resource_group_name }}"
      name: "{{ app_name }}"
      return_publish_profile: true
    register: webapp

  - name: Create Traffic Manager Profile
    azure_rm_trafficmanagerprofile:
      resource_group: "{{ resource_group_name }}"
      name: "{{ traffic_manager_profile_name }}"
      location: global
      routing_method: performance
      dns_config:
        relative_name: "{{ traffic_manager_profile_name }}"
        ttl:  60
      monitor_config:
        protocol: HTTPS
        port: 80
        path: '/'

  - name: Add endpoint to traffic manager profile, using the web site created above
    azure_rm_trafficmanagerendpoint:
      resource_group: "{{ resource_group_name }}"
      profile_name: "{{ traffic_manager_profile_name }}"
      name: "{{ traffic_manager_endpoint_name }}"
      type: azure_endpoints
      location: "{{ location }}"
      target_resource_id: "{{ webapp.webapps[0].id }}"

  - name: Get Traffic Manager Profile facts
    azure_rm_trafficmanagerprofile_facts:
      resource_group: "{{ resource_group_name }}"
      name: "{{ traffic_manager_profile_name }}"
